const actionType = Object.freeze({
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE_APP: 'CHANGE_LANGUAGE',

    SUGGESTED_ACCOUNTS_SUCCESS: 'SUGGESTED_ACCOUNTS_SUCCESS',
    SUGGESTED_ACCOUNTS_FAILED: 'SUGGESTED_ACCOUNTS_FAILED',
    SUGGESTED_ACCOUNTS_FAGE_SUCCESS: 'SUGGESTED_ACCOUNTS_FAGE_SUCCESS',

    GET_VIDEO_LIMIT_SUCCESS: 'GET_VIDEO_LIMIT_SUCCESS',
    GET_VIDEO_LIMIT_FAILED: 'GET_VIDEO_LIMIT_FAILED',
    GET_VIDEO_META_DATA_SUCCESS: 'GET_VIDEO_META_DATA_SUCCESS',
});

export default actionType;
